name: flutter_timer
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1

dev_dependencies:
  bloc_test: ^9.0.0
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  project_tailored_lints:
    path: packages/project_tailored_lints

dependency_overrides:
  analyzer: ^6.2.0
  bloc:
    path: ../../packages/bloc
  bloc_test:
    path: ../../packages/bloc_test
  flutter_bloc:
    path: ../../packages/flutter_bloc

flutter:
  uses-material-design: true
